<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="L-PG02KLQH" failures="1" tests="7" name="Test1" time="0.046" errors="0" timestamp="2022-01-18T04:44:22 PST">
  <testcase classname="com.testNG.listnerclassdemo" name="test1" time="0.005">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.testNG.listnerclassdemo" name="test2" time="0.002"/>
  <testcase classname="com.testNG.listnerclassdemo" name="test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [8] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [2]
at com.testNG.listnerclassdemo.test2(listnerclassdemo.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.testNG.listnerclassdemo" name="test2" time="0.0"/>
  <testcase classname="com.testNG.listnerclassdemo" name="test2" time="0.001"/>
  <testcase classname="com.testNG.listnerclassdemo" name="test2" time="0.001"/>
  <testcase classname="com.testNG.listnerclassdemo" name="test3" time="0.001"/>
</testsuite> <!-- Test1 -->
